### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by bharath03-a** [INFO-523-Exercises/project-final-Data-Diggers#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Vishal Bhashyaam - @vishalbhashyaam
- Joel Jojo - @joeljojo1310
- Pranshu Singh Rawat - @pranshusinghrawat
- Shashwat Singh - @shashwatsinghds
- Bharath Velamala - @bharath03-a

- **Describe the goal of the project.**
The goal of the project is to focus on early stroke detection by leveraging various classification models and interpret the output, accuracy of these models.

- **Describe the data used or collected.**
The dataset used was collected from kaggle which has a total of 4982 rows and 11 columns. It contains the information of patient's medical history, life style factors and presence or absence of stroke which can be used to determine the brain stroke likelihood. The data contains both physical and mental factors which could influence stroke likelihood like smoking_status, BMI, avg glucose level, hypertension.

- **Describe how the research question will be answered, e.g. what approaches / methods will be used.**
For both the questions they will be performing Exploratory data analysis and create visualizations to visualize different features. Then they will be implementing KNN, Random Forest and Decision Tree algorithms. They will be comparing these models on the basis of F1 score, accuracy, precision and recall to choose the best model.

- **Is there anything that is unclear from the proposal?**
The analysis plan for both the questions are combined into one. It would have been better if the plan is well defined for both of the problem statements separately.

- **Provide constructive feedback on how the team might be able to improve their project.**
It would have been more organized if the tasks were assigned to specific people and it will benefit you guys.

- **What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
We are most interested to look at how they will be able to determine which factors of lifestyle changes or medical interventions are most likely towards prevention of brain stroke.

- **Provide constructive feedback on any issues with file and/or code organization.**
It is good that they have mentioned attribute information and summarized the data in a concise manner. It would have been interesting to see numerical statistics for the features involved(eg: mean of BMI).

- **(Optional) Any further comments or feedback?**
- The project title and subtitle is really creative.
- Motivation for choosing the dataset could have been defined in a separate section instead of including it in the dataset section.

Looking forward to how this project pans out!

**Comment by KashyapNadendla** [comment]
Hi Team,

Thank you for the review. We have taken into consideration your feedback and made necessary changes.
