### ISSUE TITLE
Project proposal regrade

### ISSUE THREAD

**Issue by KashyapNadendla** [INFO-523-Exercises/project-final-Data-Diggers#4]
Hi Dr. Greg,

The Data Diggers team request you for a regrade of our project proposal. 

Data type for the attributes has been added and approach to mention that we will use classification models. We have also rephrased the vague notation you mentioned. 

Thank you for your feedback!

**Comment by Gchism94** [comment]
Good work, your final score is 9.25/10 (the mid-point between 10 and 8.5)

**Comment by KashyapNadendla** [comment]
Hi Dr. Greg,

Thank you for the regrade.
