### ISSUE TITLE
Request to wait on evaluation of website

### ISSUE THREAD

**Issue by KashyapNadendla** [INFO-523-Exercises/project-final-Data-Diggers#7]
Hi Dr. Greg,

We request you to give us time to make changes to index.qmd and add code to the repository.

Thank you!

**Comment by Gchism94** [comment]
No problem.

**Comment by KashyapNadendla** [comment]
Hi Dr. Greg,

Thank you for considering our request. As you had asked us to create a src/code folder and include the code file in it, but we are facing some strange issue with regards to uploading a new folder with the code. It is not being read by GitHub for me or my teammates. 

So, we have updated the main repository with the file - brain_stroke_classifiers.ipynb with the code chunks and output. Please refer to that file for the code. We sincerely apologize for the delay and not being able to add it in the src/code folder. Thank you so much for your feedback throughout the semester.

- Team Data Diggers
